/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dale' at '16. 9. 26 오후 8:49' with Gradle 3.1
 *
 * @author dale, @date 16. 9. 26 오후 8:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
